// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks


import mock "github.com/stretchr/testify/mock"

// ChannelResponse is an autogenerated mock type for the ChannelResponse type
type ChannelResponse struct {
	mock.Mock
}
