// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import common "github.com/inklabsfoundation/inkchain/cmd/common"

import kingpin "gopkg.in/alecthomas/kingpin.v2"
import mock "github.com/stretchr/testify/mock"

// CommandRegistrar is an autogenerated mock type for the CommandRegistrar type
type CommandRegistrar struct {
	mock.Mock
}

