// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import cmd "github.com/inklabsfoundation/inkchain/discovery/cmd"


// Stub is an autogenerated mock type for the Stub type
type Stub struct {
	mock.Mock
}

