// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/configuration.proto

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// HashingAlgorithm is encoded into the configuration transaction as  a configuration item of type Chain
// with a Key of "HashingAlgorithm" and a Value of  HashingAlgorithm as marshaled protobuf bytes
type HashingAlgorithm struct {
	// Currently supported algorithms are: SHAKE256
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HashingAlgorithm) Reset()                    { *m = HashingAlgorithm{} }
func (m *HashingAlgorithm) String() string            { return proto.CompactTextString(m) }
func (*HashingAlgorithm) ProtoMessage()               {}
func (*HashingAlgorithm) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *HashingAlgorithm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// BlockDataHashingStructure is encoded into the configuration transaction as a configuration item of
// type Chain with a Key of "BlockDataHashingStructure" and a Value of HashingAlgorithm as marshaled protobuf bytes
type BlockDataHashingStructure struct {
	// width specifies the width of the Merkle tree to use when computing the BlockDataHash
	// in order to replicate flat hashing, set this width to MAX_UINT32
	Width uint32 `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
}

func (m *BlockDataHashingStructure) Reset()                    { *m = BlockDataHashingStructure{} }
func (m *BlockDataHashingStructure) String() string            { return proto.CompactTextString(m) }
func (*BlockDataHashingStructure) ProtoMessage()               {}
func (*BlockDataHashingStructure) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *BlockDataHashingStructure) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

// OrdererAddresses is encoded into the configuration transaction as a configuration item of type Chain
// with a Key of "OrdererAddresses" and a Value of OrdererAddresses as marshaled protobuf bytes
type OrdererAddresses struct {
	Addresses []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *OrdererAddresses) Reset()                    { *m = OrdererAddresses{} }
func (m *OrdererAddresses) String() string            { return proto.CompactTextString(m) }
func (*OrdererAddresses) ProtoMessage()               {}
func (*OrdererAddresses) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *OrdererAddresses) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// Consortium represents the consortium context in which the channel was created
type Consortium struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Consortium) Reset()                    { *m = Consortium{} }
func (m *Consortium) String() string            { return proto.CompactTextString(m) }
func (*Consortium) ProtoMessage()               {}
func (*Consortium) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *Consortium) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*HashingAlgorithm)(nil), "common.HashingAlgorithm")
	proto.RegisterType((*BlockDataHashingStructure)(nil), "common.BlockDataHashingStructure")
	proto.RegisterType((*OrdererAddresses)(nil), "common.OrdererAddresses")
	proto.RegisterType((*Consortium)(nil), "common.Consortium")
}

func init() { proto.RegisterFile("common/configuration.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x09, 0xdf, 0x67, 0x21, 0x03, 0x42, 0x09, 0x1e, 0xaa, 0x78, 0x08, 0x11, 0xa4, 0xa7,
	0x44, 0xe9, 0x2f, 0x68, 0xf5, 0xe0, 0x4d, 0x88, 0xb7, 0xde, 0x36, 0xd9, 0xed, 0xee, 0x90, 0x64,
	0x46, 0x66, 0x77, 0xf1, 0xef, 0x8b, 0xbb, 0x96, 0x5e, 0xbc, 0xbd, 0xcf, 0x0c, 0x0f, 0xcc, 0x3b,
	0x70, 0x37, 0xf2, 0xb2, 0x30, 0x75, 0x23, 0xd3, 0x09, 0x6d, 0x14, 0x15, 0x90, 0xa9, 0xfd, 0x14,
	0x0e, 0x5c, 0xad, 0xf2, 0xae, 0x79, 0x84, 0xf5, 0x9b, 0xf2, 0x0e, 0xc9, 0xee, 0x67, 0xcb, 0x82,
	0xc1, 0x2d, 0x55, 0x05, 0xff, 0x49, 0x2d, 0x66, 0x53, 0xd4, 0xc5, 0xb6, 0xec, 0x53, 0x6e, 0x9e,
	0xe1, 0xf6, 0x30, 0xf3, 0x38, 0xbd, 0xaa, 0xa0, 0x7e, 0x85, 0x8f, 0x20, 0x71, 0x0c, 0x51, 0x4c,
	0x75, 0x03, 0x57, 0x5f, 0xa8, 0x83, 0x4b, 0xc6, 0x75, 0x9f, 0xa1, 0x79, 0x82, 0xf5, 0xbb, 0x68,
	0x23, 0x46, 0xf6, 0x5a, 0x8b, 0xf1, 0xde, 0xf8, 0xea, 0x1e, 0x4a, 0x75, 0x86, 0x4d, 0x51, 0xff,
	0xdb, 0x96, 0xfd, 0x65, 0xd0, 0xd4, 0x00, 0x2f, 0x4c, 0x9e, 0x25, 0x60, 0xfc, 0xf3, 0x8c, 0xc3,
	0x11, 0x1e, 0x58, 0x6c, 0x8b, 0x34, 0x8d, 0x4e, 0x21, 0x5d, 0x42, 0x6a, 0xe5, 0xdb, 0xdc, 0xea,
	0xb8, 0xb3, 0x18, 0x5c, 0x1c, 0x7e, 0xb0, 0x43, 0x9a, 0x66, 0x35, 0xf8, 0x13, 0x47, 0xd2, 0xe9,
	0x03, 0xdd, 0x59, 0xea, 0xb2, 0xd4, 0x65, 0x69, 0x58, 0x25, 0xdc, 0x7d, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xa9, 0xfb, 0xa3, 0xd9, 0x37, 0x01, 0x00, 0x00,
}
