// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/admin.proto

/*
Package peer is a generated protocol buffer package.

It is generated from these files:
	peer/admin.proto
	peer/chaincode.proto
	peer/chaincode_event.proto
	peer/chaincode_shim.proto
	peer/configuration.proto
	peer/events.proto
	peer/peer.proto
	peer/proposal.proto
	peer/proposal_response.proto
	peer/query.proto
	peer/signed_cc_dep_spec.proto
	peer/transaction.proto

It has these top-level messages:
	ServerStatus
	LogLevelRequest
	LogLevelResponse
	ChaincodeID
	ChaincodeInput
	ChaincodeSpec
	SenderSpec
	SignContent
	ChaincodeDeploymentSpec
	ChaincodeInvocationSpec
	ChaincodeEvent
	ChaincodeMessage
	PutStateInfo
	GetStateByRange
	GetQueryResult
	GetHistoryForKey
	QueryStateNext
	QueryStateClose
	QueryResultBytes
	QueryResponse
	Transfer
	TransferInfo
	IssueTokenInfo
	AnchorPeers
	AnchorPeer
	ChaincodeReg
	Interest
	Register
	Rejection
	Unregister
	SignedEvent
	Event
	PeerID
	PeerEndpoint
	SignedProposal
	Proposal
	ChaincodeHeaderExtension
	ChaincodeProposalPayload
	ChaincodeAction
	ProposalResponse
	Response
	ProposalResponsePayload
	Endorsement
	ChaincodeQueryResponse
	ChaincodeInfo
	ChannelQueryResponse
	ChannelInfo
	SignedChaincodeDeploymentSpec
	SignedTransaction
	ProcessedTransaction
	Transaction
	TransactionAction
	ChaincodeActionPayload
	ChaincodeEndorsedAction
*/
package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerStatus_StatusCode int32

const (
	ServerStatus_UNDEFINED ServerStatus_StatusCode = 0
	ServerStatus_STARTED   ServerStatus_StatusCode = 1
	ServerStatus_STOPPED   ServerStatus_StatusCode = 2
	ServerStatus_PAUSED    ServerStatus_StatusCode = 3
	ServerStatus_ERROR     ServerStatus_StatusCode = 4
	ServerStatus_UNKNOWN   ServerStatus_StatusCode = 5
)

var ServerStatus_StatusCode_name = map[int32]string{
	0: "UNDEFINED",
	1: "STARTED",
	2: "STOPPED",
	3: "PAUSED",
	4: "ERROR",
	5: "UNKNOWN",
}
var ServerStatus_StatusCode_value = map[string]int32{
	"UNDEFINED": 0,
	"STARTED":   1,
	"STOPPED":   2,
	"PAUSED":    3,
	"ERROR":     4,
	"UNKNOWN":   5,
}

func (x ServerStatus_StatusCode) String() string {
	return proto.EnumName(ServerStatus_StatusCode_name, int32(x))
}
func (ServerStatus_StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ServerStatus struct {
	Status ServerStatus_StatusCode `protobuf:"varint,1,opt,name=status,enum=protos.ServerStatus_StatusCode" json:"status,omitempty"`
}

func (m *ServerStatus) Reset()                    { *m = ServerStatus{} }
func (m *ServerStatus) String() string            { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()               {}
func (*ServerStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServerStatus) GetStatus() ServerStatus_StatusCode {
	if m != nil {
		return m.Status
	}
	return ServerStatus_UNDEFINED
}

type LogLevelRequest struct {
	LogModule string `protobuf:"bytes,1,opt,name=log_module,json=logModule" json:"log_module,omitempty"`
	LogLevel  string `protobuf:"bytes,2,opt,name=log_level,json=logLevel" json:"log_level,omitempty"`
}

func (m *LogLevelRequest) Reset()                    { *m = LogLevelRequest{} }
func (m *LogLevelRequest) String() string            { return proto.CompactTextString(m) }
func (*LogLevelRequest) ProtoMessage()               {}
func (*LogLevelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogLevelRequest) GetLogModule() string {
	if m != nil {
		return m.LogModule
	}
	return ""
}

func (m *LogLevelRequest) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

type LogLevelResponse struct {
	LogModule string `protobuf:"bytes,1,opt,name=log_module,json=logModule" json:"log_module,omitempty"`
	LogLevel  string `protobuf:"bytes,2,opt,name=log_level,json=logLevel" json:"log_level,omitempty"`
}

func (m *LogLevelResponse) Reset()                    { *m = LogLevelResponse{} }
func (m *LogLevelResponse) String() string            { return proto.CompactTextString(m) }
func (*LogLevelResponse) ProtoMessage()               {}
func (*LogLevelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogLevelResponse) GetLogModule() string {
	if m != nil {
		return m.LogModule
	}
	return ""
}

func (m *LogLevelResponse) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func init() {
	proto.RegisterType((*ServerStatus)(nil), "protos.ServerStatus")
	proto.RegisterType((*LogLevelRequest)(nil), "protos.LogLevelRequest")
	proto.RegisterType((*LogLevelResponse)(nil), "protos.LogLevelResponse")
	proto.RegisterEnum("protos.ServerStatus_StatusCode", ServerStatus_StatusCode_name, ServerStatus_StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Admin service

type AdminClient interface {
	// Return the serve status.
	GetStatus(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ServerStatus, error)
	StartServer(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ServerStatus, error)
	GetModuleLogLevel(ctx context.Context, in *LogLevelRequest, opts ...grpc.CallOption) (*LogLevelResponse, error)
	SetModuleLogLevel(ctx context.Context, in *LogLevelRequest, opts ...grpc.CallOption) (*LogLevelResponse, error)
	RevertLogLevels(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetStatus(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ServerStatus, error) {
	out := new(ServerStatus)
	err := grpc.Invoke(ctx, "/protos.Admin/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) StartServer(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ServerStatus, error) {
	out := new(ServerStatus)
	err := grpc.Invoke(ctx, "/protos.Admin/StartServer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetModuleLogLevel(ctx context.Context, in *LogLevelRequest, opts ...grpc.CallOption) (*LogLevelResponse, error) {
	out := new(LogLevelResponse)
	err := grpc.Invoke(ctx, "/protos.Admin/GetModuleLogLevel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SetModuleLogLevel(ctx context.Context, in *LogLevelRequest, opts ...grpc.CallOption) (*LogLevelResponse, error) {
	out := new(LogLevelResponse)
	err := grpc.Invoke(ctx, "/protos.Admin/SetModuleLogLevel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RevertLogLevels(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/protos.Admin/RevertLogLevels", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Admin service

type AdminServer interface {
	// Return the serve status.
	GetStatus(context.Context, *google_protobuf.Empty) (*ServerStatus, error)
	StartServer(context.Context, *google_protobuf.Empty) (*ServerStatus, error)
	GetModuleLogLevel(context.Context, *LogLevelRequest) (*LogLevelResponse, error)
	SetModuleLogLevel(context.Context, *LogLevelRequest) (*LogLevelResponse, error)
	RevertLogLevels(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Admin/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetStatus(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_StartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).StartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Admin/StartServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).StartServer(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetModuleLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetModuleLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Admin/GetModuleLogLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetModuleLogLevel(ctx, req.(*LogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SetModuleLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SetModuleLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Admin/SetModuleLogLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SetModuleLogLevel(ctx, req.(*LogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RevertLogLevels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RevertLogLevels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Admin/RevertLogLevels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RevertLogLevels(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Admin_GetStatus_Handler,
		},
		{
			MethodName: "StartServer",
			Handler:    _Admin_StartServer_Handler,
		},
		{
			MethodName: "GetModuleLogLevel",
			Handler:    _Admin_GetModuleLogLevel_Handler,
		},
		{
			MethodName: "SetModuleLogLevel",
			Handler:    _Admin_SetModuleLogLevel_Handler,
		},
		{
			MethodName: "RevertLogLevels",
			Handler:    _Admin_RevertLogLevels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peer/admin.proto",
}

func init() { proto.RegisterFile("peer/admin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x8f, 0x93, 0x40,
	0x14, 0xc7, 0x4b, 0xb5, 0x55, 0xde, 0xae, 0xee, 0x38, 0x31, 0xda, 0x74, 0x63, 0x54, 0x4e, 0x7b,
	0x1a, 0x92, 0xf5, 0xe0, 0xc1, 0x78, 0xe8, 0x2e, 0xb8, 0x1a, 0xb7, 0x94, 0x0c, 0x6d, 0x8c, 0x7a,
	0x68, 0x68, 0xfb, 0x9c, 0x92, 0x02, 0x83, 0x30, 0x34, 0xf1, 0xdf, 0xf1, 0xef, 0xf2, 0x8f, 0x31,
	0x30, 0x10, 0x8c, 0xda, 0x83, 0x71, 0x4f, 0xf3, 0x7e, 0x7c, 0xdf, 0x97, 0xc7, 0x07, 0x06, 0x48,
	0x86, 0x98, 0xdb, 0xe1, 0x26, 0x89, 0x52, 0x96, 0xe5, 0x52, 0x49, 0x3a, 0xac, 0x8f, 0x62, 0x7c,
	0x2a, 0xa4, 0x14, 0x31, 0xda, 0x75, 0xba, 0x2a, 0xbf, 0xd8, 0x98, 0x64, 0xea, 0x9b, 0x16, 0x59,
	0xdf, 0x0d, 0x38, 0x0e, 0x30, 0xdf, 0x63, 0x1e, 0xa8, 0x50, 0x95, 0x05, 0x7d, 0x09, 0xc3, 0xa2,
	0x8e, 0x46, 0xc6, 0x33, 0xe3, 0xec, 0xfe, 0xf9, 0x53, 0x2d, 0x2c, 0xd8, 0xaf, 0x2a, 0xa6, 0x8f,
	0x4b, 0xb9, 0x41, 0xde, 0xc8, 0xad, 0x8f, 0x00, 0x5d, 0x95, 0xde, 0x03, 0x73, 0xe1, 0x39, 0xee,
	0x9b, 0x77, 0x9e, 0xeb, 0x90, 0x1e, 0x3d, 0x82, 0x3b, 0xc1, 0x7c, 0xc2, 0xe7, 0xae, 0x43, 0x0c,
	0x9d, 0xcc, 0x7c, 0xdf, 0x75, 0x48, 0x9f, 0x02, 0x0c, 0xfd, 0xc9, 0x22, 0x70, 0x1d, 0x72, 0x8b,
	0x9a, 0x30, 0x70, 0x39, 0x9f, 0x71, 0x72, 0xbb, 0xd2, 0x2c, 0xbc, 0xf7, 0xde, 0xec, 0x83, 0x47,
	0x06, 0xd6, 0x14, 0x4e, 0xae, 0xa5, 0xb8, 0xc6, 0x3d, 0xc6, 0x1c, 0xbf, 0x96, 0x58, 0x28, 0xfa,
	0x04, 0x20, 0x96, 0x62, 0x99, 0xc8, 0x4d, 0x19, 0x63, 0xbd, 0xaa, 0xc9, 0xcd, 0x58, 0x8a, 0x69,
	0x5d, 0xa0, 0xa7, 0x50, 0x25, 0xcb, 0xb8, 0x1a, 0x19, 0xf5, 0xeb, 0xee, 0xdd, 0xb8, 0xb1, 0xb0,
	0x3c, 0x20, 0x9d, 0x5d, 0x91, 0xc9, 0xb4, 0xc0, 0xff, 0xf1, 0x3b, 0xff, 0xd1, 0x87, 0xc1, 0xa4,
	0x02, 0x4f, 0x5f, 0x81, 0x79, 0x85, 0xaa, 0x21, 0xf9, 0x88, 0x69, 0xf0, 0xac, 0x05, 0xcf, 0xdc,
	0x0a, 0xfc, 0xf8, 0xe1, 0xdf, 0x88, 0x5a, 0x3d, 0xfa, 0x1a, 0x8e, 0x02, 0x15, 0xe6, 0x4a, 0x97,
	0xff, 0x79, 0xfc, 0x2d, 0x3c, 0xb8, 0x42, 0xa5, 0xf7, 0x6d, 0x5f, 0x8f, 0x3e, 0x6e, 0xc5, 0xbf,
	0xf1, 0x1b, 0x8f, 0xfe, 0x6c, 0x68, 0x12, 0xda, 0x29, 0xb8, 0x19, 0xa7, 0x4b, 0x38, 0xe1, 0xb8,
	0xc7, 0x5c, 0xb5, 0xbd, 0xc3, 0x54, 0x0e, 0xd4, 0xad, 0xde, 0xc5, 0x67, 0x78, 0x2e, 0x73, 0xc1,
	0xa2, 0x74, 0xb7, 0xde, 0x86, 0x51, 0xda, 0x05, 0xcd, 0x73, 0xab, 0x1f, 0xff, 0xe2, 0xb8, 0xfe,
	0x00, 0x7e, 0xb8, 0xde, 0x85, 0x02, 0x3f, 0x9d, 0x89, 0x48, 0x6d, 0xcb, 0x15, 0x5b, 0xcb, 0xc4,
	0x6e, 0xe5, 0x5d, 0xa0, 0xe7, 0xec, 0x6a, 0x6e, 0xa5, 0x2f, 0xc9, 0x8b, 0x9f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x50, 0x40, 0x11, 0x0d, 0x3f, 0x03, 0x00, 0x00,
}
