// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/chaincode.proto

package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Confidentiality Levels
type ConfidentialityLevel int32

const (
	ConfidentialityLevel_PUBLIC       ConfidentialityLevel = 0
	ConfidentialityLevel_CONFIDENTIAL ConfidentialityLevel = 1
)

var ConfidentialityLevel_name = map[int32]string{
	0: "PUBLIC",
	1: "CONFIDENTIAL",
}
var ConfidentialityLevel_value = map[string]int32{
	"PUBLIC":       0,
	"CONFIDENTIAL": 1,
}

func (x ConfidentialityLevel) String() string {
	return proto.EnumName(ConfidentialityLevel_name, int32(x))
}
func (ConfidentialityLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ChaincodeSpec_Type int32

const (
	ChaincodeSpec_UNDEFINED ChaincodeSpec_Type = 0
	ChaincodeSpec_GOLANG    ChaincodeSpec_Type = 1
	ChaincodeSpec_NODE      ChaincodeSpec_Type = 2
	ChaincodeSpec_CAR       ChaincodeSpec_Type = 3
	ChaincodeSpec_JAVA      ChaincodeSpec_Type = 4
)

var ChaincodeSpec_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "GOLANG",
	2: "NODE",
	3: "CAR",
	4: "JAVA",
}
var ChaincodeSpec_Type_value = map[string]int32{
	"UNDEFINED": 0,
	"GOLANG":    1,
	"NODE":      2,
	"CAR":       3,
	"JAVA":      4,
}

func (x ChaincodeSpec_Type) String() string {
	return proto.EnumName(ChaincodeSpec_Type_name, int32(x))
}
func (ChaincodeSpec_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

type ChaincodeDeploymentSpec_ExecutionEnvironment int32

const (
	ChaincodeDeploymentSpec_DOCKER ChaincodeDeploymentSpec_ExecutionEnvironment = 0
	ChaincodeDeploymentSpec_SYSTEM ChaincodeDeploymentSpec_ExecutionEnvironment = 1
)

var ChaincodeDeploymentSpec_ExecutionEnvironment_name = map[int32]string{
	0: "DOCKER",
	1: "SYSTEM",
}
var ChaincodeDeploymentSpec_ExecutionEnvironment_value = map[string]int32{
	"DOCKER": 0,
	"SYSTEM": 1,
}

func (x ChaincodeDeploymentSpec_ExecutionEnvironment) String() string {
	return proto.EnumName(ChaincodeDeploymentSpec_ExecutionEnvironment_name, int32(x))
}
func (ChaincodeDeploymentSpec_ExecutionEnvironment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{5, 0}
}

// ChaincodeID contains the path as specified by the deploy transaction
// that created it as well as the hashCode that is generated by the
// system for the path. From the user level (ie, CLI, REST API and so on)
// deploy transaction is expected to provide the path and other requests
// are expected to provide the hashCode. The other value will be ignored.
// Internally, the structure could contain both values. For instance, the
// hashCode will be set when first generated using the path
type ChaincodeID struct {
	// deploy transaction will use the path
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	// all other requests will use the name (really a hashcode) generated by
	// the deploy transaction
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// user friendly version name for the chaincode
	Version string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *ChaincodeID) Reset()                    { *m = ChaincodeID{} }
func (m *ChaincodeID) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeID) ProtoMessage()               {}
func (*ChaincodeID) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ChaincodeID) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChaincodeID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChaincodeID) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Carries the chaincode function and its arguments.
// UnmarshalJSON in transaction.go converts the string-based REST/JSON input to
// the []byte-based current ChaincodeInput structure.
type ChaincodeInput struct {
	Args [][]byte `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
}

func (m *ChaincodeInput) Reset()                    { *m = ChaincodeInput{} }
func (m *ChaincodeInput) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeInput) ProtoMessage()               {}
func (*ChaincodeInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ChaincodeInput) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

// Carries the chaincode specification. This is the actual metadata required for
// defining a chaincode.
type ChaincodeSpec struct {
	Type        ChaincodeSpec_Type `protobuf:"varint,1,opt,name=type,enum=protos.ChaincodeSpec_Type" json:"type,omitempty"`
	ChaincodeId *ChaincodeID       `protobuf:"bytes,2,opt,name=chaincode_id,json=chaincodeId" json:"chaincode_id,omitempty"`
	Input       *ChaincodeInput    `protobuf:"bytes,3,opt,name=input" json:"input,omitempty"`
	Timeout     int32              `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *ChaincodeSpec) Reset()                    { *m = ChaincodeSpec{} }
func (m *ChaincodeSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeSpec) ProtoMessage()               {}
func (*ChaincodeSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ChaincodeSpec) GetType() ChaincodeSpec_Type {
	if m != nil {
		return m.Type
	}
	return ChaincodeSpec_UNDEFINED
}

func (m *ChaincodeSpec) GetChaincodeId() *ChaincodeID {
	if m != nil {
		return m.ChaincodeId
	}
	return nil
}

func (m *ChaincodeSpec) GetInput() *ChaincodeInput {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *ChaincodeSpec) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type SenderSpec struct {
	Sender   []byte `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	InkLimit []byte `protobuf:"bytes,3,opt,name=ink_limit,json=inkLimit,proto3" json:"ink_limit,omitempty"`
	Msg      []byte `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *SenderSpec) Reset()                    { *m = SenderSpec{} }
func (m *SenderSpec) String() string            { return proto.CompactTextString(m) }
func (*SenderSpec) ProtoMessage()               {}
func (*SenderSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SenderSpec) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *SenderSpec) GetInkLimit() []byte {
	if m != nil {
		return m.InkLimit
	}
	return nil
}

func (m *SenderSpec) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SignContent struct {
	ChaincodeSpec   *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincode_spec,json=chaincodeSpec" json:"chaincode_spec,omitempty"`
	IdGenerationAlg string         `protobuf:"bytes,2,opt,name=id_generation_alg,json=idGenerationAlg" json:"id_generation_alg,omitempty"`
	SenderSpec      *SenderSpec    `protobuf:"bytes,3,opt,name=sender_spec,json=senderSpec" json:"sender_spec,omitempty"`
}

func (m *SignContent) Reset()                    { *m = SignContent{} }
func (m *SignContent) String() string            { return proto.CompactTextString(m) }
func (*SignContent) ProtoMessage()               {}
func (*SignContent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *SignContent) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

func (m *SignContent) GetIdGenerationAlg() string {
	if m != nil {
		return m.IdGenerationAlg
	}
	return ""
}

func (m *SignContent) GetSenderSpec() *SenderSpec {
	if m != nil {
		return m.SenderSpec
	}
	return nil
}

// Specify the deployment of a chaincode.
// TODO: Define `codePackage`.
type ChaincodeDeploymentSpec struct {
	ChaincodeSpec *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincode_spec,json=chaincodeSpec" json:"chaincode_spec,omitempty"`
	// Controls when the chaincode becomes executable.
	EffectiveDate *google_protobuf1.Timestamp                  `protobuf:"bytes,2,opt,name=effective_date,json=effectiveDate" json:"effective_date,omitempty"`
	CodePackage   []byte                                       `protobuf:"bytes,3,opt,name=code_package,json=codePackage,proto3" json:"code_package,omitempty"`
	ExecEnv       ChaincodeDeploymentSpec_ExecutionEnvironment `protobuf:"varint,4,opt,name=exec_env,json=execEnv,enum=protos.ChaincodeDeploymentSpec_ExecutionEnvironment" json:"exec_env,omitempty"`
}

func (m *ChaincodeDeploymentSpec) Reset()                    { *m = ChaincodeDeploymentSpec{} }
func (m *ChaincodeDeploymentSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeDeploymentSpec) ProtoMessage()               {}
func (*ChaincodeDeploymentSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ChaincodeDeploymentSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetEffectiveDate() *google_protobuf1.Timestamp {
	if m != nil {
		return m.EffectiveDate
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetCodePackage() []byte {
	if m != nil {
		return m.CodePackage
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetExecEnv() ChaincodeDeploymentSpec_ExecutionEnvironment {
	if m != nil {
		return m.ExecEnv
	}
	return ChaincodeDeploymentSpec_DOCKER
}

// Carries the chaincode function and its arguments.
type ChaincodeInvocationSpec struct {
	ChaincodeSpec *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincode_spec,json=chaincodeSpec" json:"chaincode_spec,omitempty"`
	// This field can contain a user-specified ID generation algorithm
	// If supplied, this will be used to generate a ID
	// If not supplied (left empty), sha256base64 will be used
	// The algorithm consists of two parts:
	//  1, a hash function
	//  2, a decoding used to decode user (string) input to bytes
	// Currently, SHA256 with BASE64 is supported (e.g. idGenerationAlg='sha256base64')
	IdGenerationAlg string      `protobuf:"bytes,2,opt,name=id_generation_alg,json=idGenerationAlg" json:"id_generation_alg,omitempty"`
	SenderSpec      *SenderSpec `protobuf:"bytes,3,opt,name=sender_spec,json=senderSpec" json:"sender_spec,omitempty"`
	Sig             []byte      `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (m *ChaincodeInvocationSpec) Reset()                    { *m = ChaincodeInvocationSpec{} }
func (m *ChaincodeInvocationSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeInvocationSpec) ProtoMessage()               {}
func (*ChaincodeInvocationSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ChaincodeInvocationSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

func (m *ChaincodeInvocationSpec) GetIdGenerationAlg() string {
	if m != nil {
		return m.IdGenerationAlg
	}
	return ""
}

func (m *ChaincodeInvocationSpec) GetSenderSpec() *SenderSpec {
	if m != nil {
		return m.SenderSpec
	}
	return nil
}

func (m *ChaincodeInvocationSpec) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*ChaincodeID)(nil), "protos.ChaincodeID")
	proto.RegisterType((*ChaincodeInput)(nil), "protos.ChaincodeInput")
	proto.RegisterType((*ChaincodeSpec)(nil), "protos.ChaincodeSpec")
	proto.RegisterType((*SenderSpec)(nil), "protos.SenderSpec")
	proto.RegisterType((*SignContent)(nil), "protos.SignContent")
	proto.RegisterType((*ChaincodeDeploymentSpec)(nil), "protos.ChaincodeDeploymentSpec")
	proto.RegisterType((*ChaincodeInvocationSpec)(nil), "protos.ChaincodeInvocationSpec")
	proto.RegisterEnum("protos.ConfidentialityLevel", ConfidentialityLevel_name, ConfidentialityLevel_value)
	proto.RegisterEnum("protos.ChaincodeSpec_Type", ChaincodeSpec_Type_name, ChaincodeSpec_Type_value)
	proto.RegisterEnum("protos.ChaincodeDeploymentSpec_ExecutionEnvironment", ChaincodeDeploymentSpec_ExecutionEnvironment_name, ChaincodeDeploymentSpec_ExecutionEnvironment_value)
}

func init() { proto.RegisterFile("peer/chaincode.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcf, 0x6e, 0xfb, 0x44,
	0x10, 0xfe, 0xb9, 0x49, 0xff, 0x8d, 0x93, 0x60, 0x96, 0x52, 0xa2, 0x72, 0xa0, 0x58, 0x1c, 0xaa,
	0x0a, 0x39, 0x22, 0xad, 0x38, 0x21, 0xa4, 0x34, 0x76, 0x2b, 0x43, 0x48, 0xaa, 0x4d, 0x8a, 0x04,
	0x97, 0xc8, 0xb1, 0x27, 0xee, 0x2a, 0xf6, 0xae, 0x65, 0x6f, 0xa2, 0xe6, 0x9d, 0x78, 0x06, 0x1e,
	0x80, 0x97, 0x02, 0xed, 0x3a, 0x76, 0xa9, 0xd2, 0x1b, 0xfc, 0x4e, 0x9e, 0x19, 0xcf, 0xec, 0x7c,
	0xdf, 0x37, 0xb3, 0x0b, 0x67, 0x19, 0x62, 0xde, 0x0b, 0x9f, 0x03, 0xc6, 0x43, 0x11, 0xa1, 0x93,
	0xe5, 0x42, 0x0a, 0x72, 0xa4, 0x3f, 0xc5, 0xc5, 0x57, 0xb1, 0x10, 0x71, 0x82, 0x3d, 0xed, 0x2e,
	0xd6, 0xcb, 0x9e, 0x64, 0x29, 0x16, 0x32, 0x48, 0xb3, 0x32, 0xd1, 0x9e, 0x80, 0x39, 0xac, 0x6a,
	0x7d, 0x97, 0x10, 0x68, 0x66, 0x81, 0x7c, 0xee, 0x1a, 0x97, 0xc6, 0xd5, 0x29, 0xd5, 0xb6, 0x8a,
	0xf1, 0x20, 0xc5, 0xee, 0x41, 0x19, 0x53, 0x36, 0xe9, 0xc2, 0xf1, 0x06, 0xf3, 0x82, 0x09, 0xde,
	0x6d, 0xe8, 0x70, 0xe5, 0xda, 0xdf, 0x40, 0xe7, 0xf5, 0x40, 0x9e, 0xad, 0xa5, 0xaa, 0x0f, 0xf2,
	0xb8, 0xe8, 0x1a, 0x97, 0x8d, 0xab, 0x16, 0xd5, 0xb6, 0xfd, 0xb7, 0x01, 0xed, 0x3a, 0x6d, 0x9a,
	0x61, 0x48, 0x1c, 0x68, 0xca, 0x6d, 0x86, 0xba, 0x73, 0xa7, 0x7f, 0x51, 0xc2, 0x2b, 0x9c, 0x37,
	0x49, 0xce, 0x6c, 0x9b, 0x21, 0xd5, 0x79, 0xe4, 0x7b, 0x68, 0xd5, 0xa4, 0xe7, 0x2c, 0xd2, 0xe8,
	0xcc, 0xfe, 0x67, 0x7b, 0x75, 0xbe, 0x4b, 0xcd, 0x3a, 0xd1, 0x8f, 0xc8, 0xb7, 0x70, 0xc8, 0x14,
	0x2c, 0x8d, 0xdb, 0xec, 0x9f, 0xef, 0x17, 0xa8, 0xbf, 0xb4, 0x4c, 0x52, 0x3c, 0x95, 0x62, 0x62,
	0x2d, 0xbb, 0xcd, 0x4b, 0xe3, 0xea, 0x90, 0x56, 0xae, 0xfd, 0x23, 0x34, 0x15, 0x1a, 0xd2, 0x86,
	0xd3, 0xa7, 0xb1, 0xeb, 0xdd, 0xfb, 0x63, 0xcf, 0xb5, 0x3e, 0x10, 0x80, 0xa3, 0x87, 0xc9, 0x68,
	0x30, 0x7e, 0xb0, 0x0c, 0x72, 0x02, 0xcd, 0xf1, 0xc4, 0xf5, 0xac, 0x03, 0x72, 0x0c, 0x8d, 0xe1,
	0x80, 0x5a, 0x0d, 0x15, 0xfa, 0x69, 0xf0, 0xeb, 0xc0, 0x6a, 0xda, 0x29, 0xc0, 0x14, 0x79, 0x84,
	0xb9, 0x66, 0x7f, 0x0e, 0x47, 0x85, 0xf6, 0x34, 0xff, 0x16, 0xdd, 0x79, 0xaa, 0x7f, 0x28, 0xd6,
	0x5c, 0x62, 0xae, 0x09, 0x36, 0x69, 0xe5, 0x92, 0x2f, 0xe1, 0x94, 0xf1, 0xd5, 0x3c, 0x61, 0x29,
	0x2b, 0xb9, 0xb4, 0xe8, 0x09, 0xe3, 0xab, 0x91, 0xf2, 0x89, 0x05, 0x8d, 0xb4, 0x88, 0x35, 0xe4,
	0x16, 0x55, 0xa6, 0xfd, 0x87, 0x01, 0xe6, 0x94, 0xc5, 0x7c, 0x28, 0xb8, 0x44, 0x2e, 0xc9, 0x0f,
	0xd0, 0x79, 0x95, 0xaf, 0xc8, 0x30, 0xd4, 0x8d, 0xcd, 0xfe, 0xe7, 0xef, 0x0a, 0x4f, 0xdb, 0xe1,
	0x9b, 0x61, 0x5d, 0xc3, 0xa7, 0x2c, 0x9a, 0xc7, 0xc8, 0x31, 0x0f, 0x24, 0x13, 0x7c, 0x1e, 0x24,
	0xf1, 0x6e, 0x3f, 0x3e, 0x61, 0xd1, 0x43, 0x1d, 0x1f, 0x24, 0x31, 0xb9, 0x01, 0xb3, 0x24, 0x53,
	0xb6, 0x29, 0x65, 0x27, 0x55, 0x9b, 0x57, 0x0d, 0x28, 0x14, 0xb5, 0x6d, 0xff, 0x79, 0x00, 0x5f,
	0xd4, 0x08, 0x5c, 0xcc, 0x12, 0xb1, 0x4d, 0x91, 0x4b, 0xdd, 0xfc, 0xbf, 0x41, 0x1f, 0x40, 0x07,
	0x97, 0x4b, 0x0c, 0x25, 0xdb, 0xe0, 0x3c, 0x0a, 0x24, 0xee, 0x36, 0xe7, 0xc2, 0x29, 0xaf, 0x8a,
	0x53, 0x5d, 0x15, 0x67, 0x56, 0x5d, 0x15, 0xda, 0xae, 0x2b, 0xdc, 0x40, 0x22, 0xf9, 0x1a, 0x5a,
	0xba, 0x77, 0x16, 0x84, 0xab, 0x20, 0xc6, 0x9d, 0xfa, 0xa6, 0x8a, 0x3d, 0x96, 0x21, 0x32, 0x81,
	0x13, 0x7c, 0xc1, 0x70, 0x8e, 0x7c, 0xa3, 0xa7, 0xd0, 0xe9, 0xdf, 0xee, 0xa1, 0x7b, 0x4b, 0xcb,
	0xf1, 0x5e, 0x30, 0x5c, 0x2b, 0xd1, 0x3c, 0xbe, 0x61, 0xb9, 0xe0, 0xea, 0x07, 0x3d, 0x56, 0xa7,
	0x78, 0x7c, 0x63, 0x3b, 0x70, 0xf6, 0x5e, 0x82, 0xda, 0x37, 0x77, 0x32, 0xfc, 0xd9, 0xa3, 0xe5,
	0xee, 0x4d, 0x7f, 0x9b, 0xce, 0xbc, 0x5f, 0x2c, 0xc3, 0xfe, 0xcb, 0xf8, 0x97, 0x80, 0x3e, 0xdf,
	0x88, 0x50, 0x0f, 0xe4, 0x7f, 0x10, 0xf0, 0x63, 0xcf, 0x5e, 0x2d, 0x6f, 0xc1, 0xea, 0xe5, 0x2d,
	0x58, 0x7c, 0x7d, 0x0b, 0x67, 0x43, 0xc1, 0x97, 0x2c, 0x42, 0x2e, 0x59, 0x90, 0x30, 0xb9, 0x1d,
	0xe1, 0x06, 0x13, 0x45, 0xf8, 0xf1, 0xe9, 0x6e, 0xe4, 0x0f, 0xad, 0x0f, 0xc4, 0x82, 0xd6, 0x70,
	0x32, 0xbe, 0xf7, 0x5d, 0x6f, 0x3c, 0xf3, 0x07, 0x23, 0xcb, 0xb8, 0x9b, 0xc3, 0xb5, 0xc8, 0x63,
	0x87, 0xf1, 0x55, 0x12, 0x2c, 0x8a, 0xa5, 0x58, 0xf3, 0x48, 0x03, 0x53, 0x11, 0x4d, 0xa9, 0xc2,
	0xa1, 0x5e, 0xd0, 0xdf, 0xbf, 0x8b, 0x99, 0x7c, 0x5e, 0x2f, 0x9c, 0x50, 0xa4, 0xbd, 0xbd, 0x92,
	0x5e, 0x55, 0x52, 0x3e, 0xa4, 0x45, 0x4f, 0x95, 0x2c, 0xca, 0x47, 0xf6, 0xe6, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb3, 0xc7, 0xcc, 0x87, 0x83, 0x05, 0x00, 0x00,
}
