// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/proposal_response.proto

package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A ProposalResponse is returned from an endorser to the proposal submitter.
// The idea is that this message contains the endorser's response to the
// request of a client to perform an action over a chaincode (or more
// generically on the ledger); the response might be success/error (conveyed in
// the Response field) together with a description of the action and a
// signature over it by that endorser.  If a sufficient number of distinct
// endorsers agree on the same action and produce signature to that effect, a
// transaction can be generated and sent for ordering.
type ProposalResponse struct {
	// Version indicates message protocol version
	Version int32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	// Timestamp is the time that the message
	// was created as  defined by the sender
	Timestamp *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// A response message indicating whether the
	// endorsement of the action was successful
	Response *Response `protobuf:"bytes,4,opt,name=response" json:"response,omitempty"`
	// The payload of response. It is the bytes of ProposalResponsePayload
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// The endorsement of the proposal, basically
	// the endorser's signature over the payload
	Endorsement *Endorsement `protobuf:"bytes,6,opt,name=endorsement" json:"endorsement,omitempty"`
}

func (m *ProposalResponse) Reset()                    { *m = ProposalResponse{} }
func (m *ProposalResponse) String() string            { return proto.CompactTextString(m) }
func (*ProposalResponse) ProtoMessage()               {}
func (*ProposalResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *ProposalResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ProposalResponse) GetTimestamp() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ProposalResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ProposalResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ProposalResponse) GetEndorsement() *Endorsement {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

// A response with a representation similar to an HTTP response that can
// be used within another message.
type Response struct {
	// A status code that should follow the HTTP status codes.
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	// A message associated with the response code.
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// A payload that can be used to include metadata with this response.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// ProposalResponsePayload is the payload of a proposal response.  This message
// is the "bridge" between the client's request and the endorser's action in
// response to that request. Concretely, for chaincodes, it contains a hashed
// representation of the proposal (proposalHash) and a representation of the
// chaincode state changes and events inside the extension field.
type ProposalResponsePayload struct {
	// Hash of the proposal that triggered this response. The hash is used to
	// link a response with its proposal, both for bookeeping purposes on an
	// asynchronous system and for security reasons (accountability,
	// non-repudiation). The hash usually covers the entire Proposal message
	// (byte-by-byte). However this implies that the hash can only be verified
	// if the entire proposal message is available when ProposalResponsePayload is
	// included in a transaction or stored in the ledger. For confidentiality
	// reasons, with chaincodes it might be undesirable to store the proposal
	// payload in the ledger.  If the type is CHAINCODE, this is handled by
	// separating the proposal's header and
	// the payload: the header is always hashed in its entirety whereas the
	// payload can either be hashed fully, or only its hash may be hashed, or
	// nothing from the payload can be hashed. The PayloadVisibility field in the
	// Header's extension controls to which extent the proposal payload is
	// "visible" in the sense that was just explained.
	ProposalHash []byte `protobuf:"bytes,1,opt,name=proposal_hash,json=proposalHash,proto3" json:"proposal_hash,omitempty"`
	// Extension should be unmarshaled to a type-specific message. The type of
	// the extension in any proposal response depends on the type of the proposal
	// that the client selected when the proposal was initially sent out.  In
	// particular, this information is stored in the type field of a Header.  For
	// chaincode, it's a ChaincodeAction message
	Extension []byte `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
}

func (m *ProposalResponsePayload) Reset()                    { *m = ProposalResponsePayload{} }
func (m *ProposalResponsePayload) String() string            { return proto.CompactTextString(m) }
func (*ProposalResponsePayload) ProtoMessage()               {}
func (*ProposalResponsePayload) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *ProposalResponsePayload) GetProposalHash() []byte {
	if m != nil {
		return m.ProposalHash
	}
	return nil
}

func (m *ProposalResponsePayload) GetExtension() []byte {
	if m != nil {
		return m.Extension
	}
	return nil
}

// An endorsement is a signature of an endorser over a proposal response.  By
// producing an endorsement message, an endorser implicitly "approves" that
// proposal response and the actions contained therein. When enough
// endorsements have been collected, a transaction can be generated out of a
// set of proposal responses.  Note that this message only contains an identity
// and a signature but no signed payload. This is intentional because
// endorsements are supposed to be collected in a transaction, and they are all
// expected to endorse a single proposal response/action (many endorsements
// over a single proposal response)
type Endorsement struct {
	// Identity of the endorser (e.g. its certificate)
	Endorser []byte `protobuf:"bytes,1,opt,name=endorser,proto3" json:"endorser,omitempty"`
	// Signature of the payload included in ProposalResponse concatenated with
	// the endorser's certificate; ie, sign(ProposalResponse.payload + endorser)
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Endorsement) Reset()                    { *m = Endorsement{} }
func (m *Endorsement) String() string            { return proto.CompactTextString(m) }
func (*Endorsement) ProtoMessage()               {}
func (*Endorsement) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *Endorsement) GetEndorser() []byte {
	if m != nil {
		return m.Endorser
	}
	return nil
}

func (m *Endorsement) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*ProposalResponse)(nil), "protos.ProposalResponse")
	proto.RegisterType((*Response)(nil), "protos.Response")
	proto.RegisterType((*ProposalResponsePayload)(nil), "protos.ProposalResponsePayload")
	proto.RegisterType((*Endorsement)(nil), "protos.Endorsement")
}

func init() { proto.RegisterFile("peer/proposal_response.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5f, 0x4b, 0xeb, 0x40,
	0x10, 0xc5, 0x49, 0xef, 0x6d, 0x6f, 0xbb, 0xed, 0x85, 0x12, 0x41, 0x43, 0x29, 0x58, 0xe2, 0x4b,
	0x11, 0x49, 0x50, 0x11, 0x7c, 0x2e, 0x88, 0x3e, 0x96, 0x45, 0x7c, 0x10, 0x41, 0x36, 0xed, 0x34,
	0x09, 0x4d, 0x76, 0xc2, 0xce, 0x46, 0xea, 0x07, 0xf6, 0x7b, 0x48, 0x36, 0xd9, 0xb4, 0xfe, 0x79,
	0x2a, 0x67, 0x7a, 0xf6, 0x37, 0x73, 0x26, 0xc3, 0xa6, 0x05, 0x80, 0x0a, 0x0b, 0x85, 0x05, 0x92,
	0xc8, 0x5e, 0x15, 0x50, 0x81, 0x92, 0x20, 0x28, 0x14, 0x6a, 0x74, 0x7b, 0xe6, 0x87, 0x26, 0xa7,
	0x31, 0x62, 0x9c, 0x41, 0x68, 0x64, 0x54, 0x6e, 0x42, 0x9d, 0xe6, 0x40, 0x5a, 0xe4, 0x45, 0x6d,
	0xf4, 0x3f, 0x1c, 0x36, 0x5e, 0x36, 0x10, 0xde, 0x30, 0x5c, 0x8f, 0xfd, 0x7b, 0x03, 0x45, 0x29,
	0x4a, 0xcf, 0x99, 0x39, 0xf3, 0x2e, 0xb7, 0xd2, 0xbd, 0x65, 0x83, 0x96, 0xe0, 0x75, 0x66, 0xce,
	0x7c, 0x78, 0x35, 0x09, 0xea, 0x1e, 0x81, 0xed, 0x11, 0x3c, 0x5a, 0x07, 0xdf, 0x9b, 0xdd, 0x0b,
	0xd6, 0xb7, 0x33, 0x7a, 0x7f, 0xcd, 0xc3, 0x71, 0xfd, 0x82, 0x02, 0xdb, 0x97, 0xb7, 0x8e, 0x6a,
	0x82, 0x42, 0xbc, 0x67, 0x28, 0xd6, 0x5e, 0x77, 0xe6, 0xcc, 0x47, 0xdc, 0x4a, 0xf7, 0x86, 0x0d,
	0x41, 0xae, 0x51, 0x11, 0xe4, 0x20, 0xb5, 0xd7, 0x33, 0xa8, 0x23, 0x8b, 0xba, 0xdb, 0xff, 0xc5,
	0x0f, 0x7d, 0xfe, 0x13, 0xeb, 0xb7, 0xf1, 0x8e, 0x59, 0x8f, 0xb4, 0xd0, 0x25, 0x35, 0xe9, 0x1a,
	0x55, 0x35, 0xcd, 0x81, 0x48, 0xc4, 0x60, 0xa2, 0x0d, 0xb8, 0x95, 0x87, 0xe3, 0xfc, 0xf9, 0x32,
	0x8e, 0xff, 0xc2, 0x4e, 0xbe, 0xaf, 0x6f, 0xd9, 0x4c, 0x7a, 0xc6, 0xfe, 0xb7, 0x9f, 0x27, 0x11,
	0x94, 0x98, 0x6e, 0x23, 0x3e, 0xb2, 0xc5, 0x07, 0x41, 0x89, 0x3b, 0x65, 0x03, 0xd8, 0x69, 0x90,
	0x66, 0xd9, 0x1d, 0x63, 0xd8, 0x17, 0xfc, 0x7b, 0x36, 0x3c, 0x48, 0xe4, 0x4e, 0x58, 0xbf, 0xc9,
	0xa4, 0x1a, 0x58, 0xab, 0x2b, 0x10, 0xa5, 0xb1, 0x14, 0xba, 0x54, 0x60, 0x41, 0x6d, 0x61, 0xb1,
	0x63, 0xe7, 0xa8, 0xe2, 0x20, 0x95, 0xdb, 0x4c, 0x44, 0xb4, 0xc1, 0x52, 0xae, 0x85, 0x4e, 0x51,
	0x56, 0x95, 0x55, 0x22, 0x52, 0x69, 0x17, 0x58, 0x5d, 0xd5, 0xe2, 0x97, 0x48, 0xab, 0xad, 0x88,
	0xe1, 0xf9, 0x32, 0x4e, 0x75, 0x52, 0x46, 0xc1, 0x0a, 0xf3, 0xf0, 0x07, 0x2b, 0xb4, 0xac, 0xfa,
	0xda, 0x28, 0xac, 0x58, 0x51, 0x7d, 0x89, 0xd7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x54, 0x3b,
	0xab, 0x00, 0xb0, 0x02, 0x00, 0x00,
}
