// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/query.proto

package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ChaincodeQueryResponse returns information about each chaincode that pertains
// to a query in lscc.go, such as GetChaincodes (returns all chaincodes
// instantiated on a channel), and GetInstalledChaincodes (returns all chaincodes
// installed on a peer)
type ChaincodeQueryResponse struct {
	Chaincodes []*ChaincodeInfo `protobuf:"bytes,1,rep,name=chaincodes" json:"chaincodes,omitempty"`
}

func (m *ChaincodeQueryResponse) Reset()                    { *m = ChaincodeQueryResponse{} }
func (m *ChaincodeQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeQueryResponse) ProtoMessage()               {}
func (*ChaincodeQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *ChaincodeQueryResponse) GetChaincodes() []*ChaincodeInfo {
	if m != nil {
		return m.Chaincodes
	}
	return nil
}

// ChaincodeInfo contains general information about an installed/instantiated
// chaincode
type ChaincodeInfo struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	// the path as specified by the install/instantiate transaction
	Path string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	// the chaincode function upon instantiation and its arguments. This will be
	// blank if the query is returning information about installed chaincodes.
	Input string `protobuf:"bytes,4,opt,name=input" json:"input,omitempty"`
	// the name of the ESCC for this chaincode. This will be
	// blank if the query is returning information about installed chaincodes.
	Escc string `protobuf:"bytes,5,opt,name=escc" json:"escc,omitempty"`
	// the name of the VSCC for this chaincode. This will be
	// blank if the query is returning information about installed chaincodes.
	Vscc string `protobuf:"bytes,6,opt,name=vscc" json:"vscc,omitempty"`
}

func (m *ChaincodeInfo) Reset()                    { *m = ChaincodeInfo{} }
func (m *ChaincodeInfo) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeInfo) ProtoMessage()               {}
func (*ChaincodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *ChaincodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChaincodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ChaincodeInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChaincodeInfo) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *ChaincodeInfo) GetEscc() string {
	if m != nil {
		return m.Escc
	}
	return ""
}

func (m *ChaincodeInfo) GetVscc() string {
	if m != nil {
		return m.Vscc
	}
	return ""
}

// ChannelQueryResponse returns information about each channel that pertains
// to a query in lscc.go, such as GetChannels (returns all channels for a
// given peer)
type ChannelQueryResponse struct {
	Channels []*ChannelInfo `protobuf:"bytes,1,rep,name=channels" json:"channels,omitempty"`
}

func (m *ChannelQueryResponse) Reset()                    { *m = ChannelQueryResponse{} }
func (m *ChannelQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*ChannelQueryResponse) ProtoMessage()               {}
func (*ChannelQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *ChannelQueryResponse) GetChannels() []*ChannelInfo {
	if m != nil {
		return m.Channels
	}
	return nil
}

// ChannelInfo contains general information about channels
type ChannelInfo struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
}

func (m *ChannelInfo) Reset()                    { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string            { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()               {}
func (*ChannelInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

func (m *ChannelInfo) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func init() {
	proto.RegisterType((*ChaincodeQueryResponse)(nil), "protos.ChaincodeQueryResponse")
	proto.RegisterType((*ChaincodeInfo)(nil), "protos.ChaincodeInfo")
	proto.RegisterType((*ChannelQueryResponse)(nil), "protos.ChannelQueryResponse")
	proto.RegisterType((*ChannelInfo)(nil), "protos.ChannelInfo")
}

func init() { proto.RegisterFile("peer/query.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xa9, 0xfb, 0xa1, 0x7b, 0x43, 0x90, 0x38, 0x25, 0x17, 0x61, 0xf6, 0xd4, 0x83, 0xb4,
	0xa0, 0xf8, 0x0f, 0xb8, 0x83, 0xec, 0x20, 0x62, 0x8f, 0x5e, 0xa4, 0x4b, 0x9f, 0x6b, 0xd0, 0x25,
	0x31, 0x69, 0x07, 0xfe, 0x15, 0xfe, 0xcb, 0xf2, 0x92, 0x76, 0x6b, 0x4f, 0xfd, 0xbe, 0xcf, 0xfb,
	0x84, 0xf2, 0x4d, 0xe0, 0xc2, 0x20, 0xda, 0xec, 0xa7, 0x41, 0xfb, 0x9b, 0x1a, 0xab, 0x6b, 0xcd,
	0xa6, 0xfe, 0xe3, 0xe2, 0x57, 0xb8, 0x5e, 0x55, 0x85, 0x54, 0x42, 0x97, 0xf8, 0x46, 0xfb, 0x1c,
	0x9d, 0xd1, 0xca, 0x21, 0x7b, 0x04, 0x10, 0xdd, 0xc6, 0xf1, 0x68, 0x39, 0x4a, 0xe6, 0xf7, 0x57,
	0xe1, 0xb4, 0x4b, 0x0f, 0x67, 0xd6, 0xea, 0x53, 0xe7, 0x3d, 0x31, 0xfe, 0x8b, 0xe0, 0x7c, 0xb0,
	0x65, 0x0c, 0xc6, 0xaa, 0xd8, 0x21, 0x8f, 0x96, 0x51, 0x32, 0xcb, 0x7d, 0x66, 0x1c, 0x4e, 0xf7,
	0x68, 0x9d, 0xd4, 0x8a, 0x9f, 0x78, 0xdc, 0x8d, 0x64, 0x9b, 0xa2, 0xae, 0xf8, 0x28, 0xd8, 0x94,
	0xd9, 0x02, 0x26, 0x52, 0x99, 0xa6, 0xe6, 0x63, 0x0f, 0xc3, 0x40, 0x26, 0x3a, 0x21, 0xf8, 0x24,
	0x98, 0x94, 0x89, 0xed, 0x89, 0x4d, 0x03, 0xa3, 0x1c, 0x3f, 0xc3, 0x62, 0x55, 0x15, 0x4a, 0xe1,
	0xf7, 0xb0, 0x60, 0x06, 0x67, 0x22, 0xf0, 0xae, 0xde, 0x65, 0xaf, 0x1e, 0x71, 0x5f, 0xee, 0x20,
	0xc5, 0x77, 0x30, 0xef, 0x2d, 0xd8, 0x8d, 0xbf, 0x20, 0x1a, 0x3f, 0x64, 0xd9, 0xb6, 0x9b, 0xb5,
	0x64, 0x5d, 0x3e, 0xbd, 0xc0, 0xad, 0xb6, 0xdb, 0x54, 0xaa, 0x2f, 0x7f, 0x3b, 0xc7, 0xd0, 0xfe,
	0x83, 0x9e, 0xe4, 0x3d, 0xd9, 0xca, 0xba, 0x6a, 0x36, 0xa9, 0xd0, 0xbb, 0xac, 0x13, 0x8e, 0x21,
	0x98, 0x19, 0x99, 0x9b, 0xf0, 0x60, 0x0f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xb6, 0x78,
	0x91, 0xcb, 0x01, 0x00, 0x00,
}
