// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

/*
Package testprotos is a generated protocol buffer package.

It is generated from these files:
	sample.proto

It has these top-level messages:
	SimpleMsg
	NestedMsg
	StaticallyOpaqueMsg
	VariablyOpaqueMsg
	DynamicMsg
	ContextlessMsg
*/
package testprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SimpleMsg is designed to test that all three types of message fields, plain, map,
// and slice are handled by the protolator tool
type SimpleMsg struct {
	PlainField string            `protobuf:"bytes,1,opt,name=plain_field,json=plainField" json:"plain_field,omitempty"`
	MapField   map[string]string `protobuf:"bytes,2,rep,name=map_field,json=mapField" json:"map_field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SliceField []string          `protobuf:"bytes,3,rep,name=slice_field,json=sliceField" json:"slice_field,omitempty"`
}

func (m *SimpleMsg) Reset()                    { *m = SimpleMsg{} }
func (m *SimpleMsg) String() string            { return proto.CompactTextString(m) }
func (*SimpleMsg) ProtoMessage()               {}
func (*SimpleMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SimpleMsg) GetPlainField() string {
	if m != nil {
		return m.PlainField
	}
	return ""
}

func (m *SimpleMsg) GetMapField() map[string]string {
	if m != nil {
		return m.MapField
	}
	return nil
}

func (m *SimpleMsg) GetSliceField() []string {
	if m != nil {
		return m.SliceField
	}
	return nil
}

// NestedMsg is designed to test the nested message component
type NestedMsg struct {
	PlainNestedField *SimpleMsg            `protobuf:"bytes,1,opt,name=plain_nested_field,json=plainNestedField" json:"plain_nested_field,omitempty"`
	MapNestedField   map[string]*SimpleMsg `protobuf:"bytes,2,rep,name=map_nested_field,json=mapNestedField" json:"map_nested_field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SliceNestedField []*SimpleMsg          `protobuf:"bytes,3,rep,name=slice_nested_field,json=sliceNestedField" json:"slice_nested_field,omitempty"`
}

func (m *NestedMsg) Reset()                    { *m = NestedMsg{} }
func (m *NestedMsg) String() string            { return proto.CompactTextString(m) }
func (*NestedMsg) ProtoMessage()               {}
func (*NestedMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NestedMsg) GetPlainNestedField() *SimpleMsg {
	if m != nil {
		return m.PlainNestedField
	}
	return nil
}

func (m *NestedMsg) GetMapNestedField() map[string]*SimpleMsg {
	if m != nil {
		return m.MapNestedField
	}
	return nil
}

func (m *NestedMsg) GetSliceNestedField() []*SimpleMsg {
	if m != nil {
		return m.SliceNestedField
	}
	return nil
}

// StaticallyOpaqueMsg is designed to test the statically opaque message component
// All fields are statically marshaled to the NestedMsg type
type StaticallyOpaqueMsg struct {
	PlainOpaqueField []byte            `protobuf:"bytes,1,opt,name=plain_opaque_field,json=plainOpaqueField,proto3" json:"plain_opaque_field,omitempty"`
	MapOpaqueField   map[string][]byte `protobuf:"bytes,2,rep,name=map_opaque_field,json=mapOpaqueField" json:"map_opaque_field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SliceOpaqueField [][]byte          `protobuf:"bytes,3,rep,name=slice_opaque_field,json=sliceOpaqueField,proto3" json:"slice_opaque_field,omitempty"`
}

func (m *StaticallyOpaqueMsg) Reset()                    { *m = StaticallyOpaqueMsg{} }
func (m *StaticallyOpaqueMsg) String() string            { return proto.CompactTextString(m) }
func (*StaticallyOpaqueMsg) ProtoMessage()               {}
func (*StaticallyOpaqueMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StaticallyOpaqueMsg) GetPlainOpaqueField() []byte {
	if m != nil {
		return m.PlainOpaqueField
	}
	return nil
}

func (m *StaticallyOpaqueMsg) GetMapOpaqueField() map[string][]byte {
	if m != nil {
		return m.MapOpaqueField
	}
	return nil
}

func (m *StaticallyOpaqueMsg) GetSliceOpaqueField() [][]byte {
	if m != nil {
		return m.SliceOpaqueField
	}
	return nil
}

// VariablyOpaqueMsg is designed to test the staticaly opaque message component
// The opaque type is determined by opaque_type
type VariablyOpaqueMsg struct {
	OpaqueType       string            `protobuf:"bytes,1,opt,name=opaque_type,json=opaqueType" json:"opaque_type,omitempty"`
	PlainOpaqueField []byte            `protobuf:"bytes,2,opt,name=plain_opaque_field,json=plainOpaqueField,proto3" json:"plain_opaque_field,omitempty"`
	MapOpaqueField   map[string][]byte `protobuf:"bytes,3,rep,name=map_opaque_field,json=mapOpaqueField" json:"map_opaque_field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SliceOpaqueField [][]byte          `protobuf:"bytes,4,rep,name=slice_opaque_field,json=sliceOpaqueField,proto3" json:"slice_opaque_field,omitempty"`
}

func (m *VariablyOpaqueMsg) Reset()                    { *m = VariablyOpaqueMsg{} }
func (m *VariablyOpaqueMsg) String() string            { return proto.CompactTextString(m) }
func (*VariablyOpaqueMsg) ProtoMessage()               {}
func (*VariablyOpaqueMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VariablyOpaqueMsg) GetOpaqueType() string {
	if m != nil {
		return m.OpaqueType
	}
	return ""
}

func (m *VariablyOpaqueMsg) GetPlainOpaqueField() []byte {
	if m != nil {
		return m.PlainOpaqueField
	}
	return nil
}

func (m *VariablyOpaqueMsg) GetMapOpaqueField() map[string][]byte {
	if m != nil {
		return m.MapOpaqueField
	}
	return nil
}

func (m *VariablyOpaqueMsg) GetSliceOpaqueField() [][]byte {
	if m != nil {
		return m.SliceOpaqueField
	}
	return nil
}

// DynamicMsg is designed to test the dynamic message component
// The dynamic wrapper applied to ContextlessMsg is determined by
// dynamic_type
type DynamicMsg struct {
	DynamicType       string                     `protobuf:"bytes,1,opt,name=dynamic_type,json=dynamicType" json:"dynamic_type,omitempty"`
	PlainDynamicField *ContextlessMsg            `protobuf:"bytes,2,opt,name=plain_dynamic_field,json=plainDynamicField" json:"plain_dynamic_field,omitempty"`
	MapDynamicField   map[string]*ContextlessMsg `protobuf:"bytes,3,rep,name=map_dynamic_field,json=mapDynamicField" json:"map_dynamic_field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SliceDynamicField []*ContextlessMsg          `protobuf:"bytes,4,rep,name=slice_dynamic_field,json=sliceDynamicField" json:"slice_dynamic_field,omitempty"`
}

func (m *DynamicMsg) Reset()                    { *m = DynamicMsg{} }
func (m *DynamicMsg) String() string            { return proto.CompactTextString(m) }
func (*DynamicMsg) ProtoMessage()               {}
func (*DynamicMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DynamicMsg) GetDynamicType() string {
	if m != nil {
		return m.DynamicType
	}
	return ""
}

func (m *DynamicMsg) GetPlainDynamicField() *ContextlessMsg {
	if m != nil {
		return m.PlainDynamicField
	}
	return nil
}

func (m *DynamicMsg) GetMapDynamicField() map[string]*ContextlessMsg {
	if m != nil {
		return m.MapDynamicField
	}
	return nil
}

func (m *DynamicMsg) GetSliceDynamicField() []*ContextlessMsg {
	if m != nil {
		return m.SliceDynamicField
	}
	return nil
}

// ContextlessMsg is designed to carry a message of completely arbitrary type
// Because there is no context for the type embedded in the message, the opaque
// type must be dynamically added at runtime
type ContextlessMsg struct {
	OpaqueField []byte `protobuf:"bytes,1,opt,name=opaque_field,json=opaqueField,proto3" json:"opaque_field,omitempty"`
}

func (m *ContextlessMsg) Reset()                    { *m = ContextlessMsg{} }
func (m *ContextlessMsg) String() string            { return proto.CompactTextString(m) }
func (*ContextlessMsg) ProtoMessage()               {}
func (*ContextlessMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ContextlessMsg) GetOpaqueField() []byte {
	if m != nil {
		return m.OpaqueField
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleMsg)(nil), "testprotos.SimpleMsg")
	proto.RegisterType((*NestedMsg)(nil), "testprotos.NestedMsg")
	proto.RegisterType((*StaticallyOpaqueMsg)(nil), "testprotos.StaticallyOpaqueMsg")
	proto.RegisterType((*VariablyOpaqueMsg)(nil), "testprotos.VariablyOpaqueMsg")
	proto.RegisterType((*DynamicMsg)(nil), "testprotos.DynamicMsg")
	proto.RegisterType((*ContextlessMsg)(nil), "testprotos.ContextlessMsg")
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xd5, 0x64, 0x20, 0xfa, 0x12, 0x46, 0x9b, 0x0e, 0x69, 0xca, 0x65, 0x65, 0x5c, 0x86,
	0x36, 0xa5, 0xd0, 0x5e, 0x10, 0x1c, 0x60, 0x0c, 0x38, 0x20, 0x0d, 0xa4, 0x16, 0x01, 0x02, 0x01,
	0x72, 0x53, 0xb3, 0x59, 0x73, 0xe2, 0xd0, 0xb8, 0x88, 0xdc, 0xf8, 0x0e, 0x7c, 0x11, 0x3e, 0x04,
	0x47, 0x3e, 0x14, 0xf2, 0xb3, 0xbb, 0xd8, 0x2c, 0x2d, 0x07, 0xc4, 0x29, 0xf6, 0xb3, 0xdf, 0xff,
	0xfd, 0xdf, 0x2f, 0xcf, 0x10, 0x96, 0x24, 0x2b, 0x38, 0x4d, 0x8a, 0xb9, 0x90, 0x22, 0x02, 0x49,
	0x4b, 0x89, 0xcb, 0x72, 0xf7, 0x57, 0x0b, 0xda, 0x13, 0xa6, 0x0e, 0x8f, 0xcb, 0x93, 0x68, 0x07,
	0x82, 0x82, 0x13, 0x96, 0x7f, 0xfc, 0xc4, 0x28, 0x9f, 0x6d, 0xb7, 0xfa, 0xad, 0xbd, 0xf6, 0x18,
	0x30, 0xf4, 0x54, 0x45, 0xa2, 0x87, 0xd0, 0xce, 0x48, 0x61, 0x8e, 0xbd, 0xbe, 0xbf, 0x17, 0x0c,
	0x6f, 0x26, 0xb5, 0x5c, 0x72, 0x2e, 0x95, 0x1c, 0x93, 0x02, 0x53, 0x9e, 0xe4, 0x72, 0x5e, 0x8d,
	0xaf, 0x64, 0x66, 0xab, 0x4a, 0x94, 0x9c, 0xa5, 0xd4, 0x68, 0xf8, 0x7d, 0x5f, 0x95, 0xc0, 0x10,
	0x5e, 0x88, 0xef, 0xc3, 0x55, 0x27, 0x37, 0xea, 0x80, 0x7f, 0x46, 0x2b, 0x63, 0x46, 0x2d, 0xa3,
	0x2d, 0xb8, 0xf4, 0x85, 0xf0, 0x05, 0xdd, 0xf6, 0x30, 0xa6, 0x37, 0xf7, 0xbc, 0xbb, 0xad, 0xdd,
	0x9f, 0x1e, 0xb4, 0x9f, 0xd3, 0x52, 0xd2, 0x99, 0x6a, 0xe7, 0x08, 0x22, 0xdd, 0x4e, 0x8e, 0x21,
	0xab, 0xab, 0x60, 0x78, 0xbd, 0xd1, 0xf6, 0xb8, 0x83, 0x09, 0x5a, 0x42, 0x1b, 0x9e, 0x40, 0x47,
	0xb5, 0xec, 0x48, 0xe8, 0xce, 0x6f, 0xd9, 0x12, 0xe7, 0x55, 0x55, 0xe7, 0x56, 0xbe, 0xee, 0x7f,
	0x33, 0x73, 0x82, 0xca, 0x99, 0xa6, 0xe0, 0xc8, 0xfa, 0x28, 0xbb, 0xca, 0x19, 0x26, 0x58, 0x22,
	0xf1, 0x1b, 0xe8, 0x35, 0xd4, 0x6a, 0xe0, 0xb5, 0x6f, 0xf3, 0x5a, 0x59, 0xc0, 0xc2, 0xf8, 0xdd,
	0x83, 0xde, 0x44, 0x12, 0xc9, 0x52, 0xc2, 0x79, 0xf5, 0xa2, 0x20, 0x9f, 0x17, 0x38, 0x1f, 0x07,
	0x4b, 0xa0, 0x02, 0x43, 0x16, 0xd0, 0xd0, 0x90, 0xd3, 0x77, 0x75, 0x93, 0xef, 0x35, 0x39, 0xe7,
	0xae, 0x26, 0x37, 0x72, 0x1c, 0x5c, 0x2c, 0xa4, 0x18, 0x5a, 0x4a, 0x35, 0x43, 0x5b, 0xfe, 0x60,
	0xc9, 0xd0, 0x29, 0xa0, 0x18, 0x86, 0x06, 0x96, 0x75, 0x3b, 0x3e, 0x44, 0x58, 0x7f, 0x8a, 0xfe,
	0x6d, 0xb8, 0x42, 0x9b, 0xca, 0x0f, 0x0f, 0xba, 0xaf, 0xc8, 0x9c, 0x91, 0xa9, 0xcd, 0x64, 0x07,
	0x02, 0x63, 0x40, 0x56, 0x05, 0x5d, 0xbe, 0x19, 0x1d, 0x7a, 0x59, 0x15, 0x74, 0x05, 0x34, 0x6f,
	0x05, 0xb4, 0x77, 0x0d, 0xd0, 0xf4, 0x5c, 0xdc, 0xb1, 0xa1, 0x5d, 0xf0, 0xf1, 0x0f, 0xc8, 0x36,
	0xfe, 0x1f, 0xb2, 0x6f, 0x3e, 0xc0, 0xe3, 0x2a, 0x27, 0x19, 0x4b, 0x15, 0xab, 0x1b, 0x10, 0xce,
	0xf4, 0xce, 0x86, 0x15, 0x98, 0x18, 0xd2, 0x7a, 0x06, 0x3d, 0x4d, 0x6b, 0x79, 0xb1, 0xc6, 0x15,
	0x0c, 0x63, 0x1b, 0xc1, 0x91, 0xc8, 0x25, 0xfd, 0x2a, 0x39, 0x2d, 0x4b, 0x35, 0xbe, 0x5d, 0x4c,
	0x33, 0xc5, 0x74, 0xbb, 0xaf, 0xa1, 0xab, 0x58, 0xba, 0x4a, 0x1a, 0xe6, 0xbe, 0xad, 0x54, 0x3b,
	0x54, 0x14, 0x6d, 0x09, 0x8d, 0xf1, 0x5a, 0xe6, 0x46, 0x95, 0x49, 0xcd, 0xd1, 0x95, 0xde, 0x40,
	0xe9, 0xb5, 0x26, 0x31, 0xcd, 0xd6, 0x8a, 0x3f, 0xc0, 0x56, 0x53, 0xd1, 0x06, 0xcc, 0xb7, 0xdd,
	0x67, 0xbc, 0xae, 0x8e, 0xf5, 0x0b, 0x46, 0xb0, 0xe9, 0x1e, 0xaa, 0xbf, 0xd0, 0xf0, 0x7e, 0xcd,
	0x14, 0xa3, 0x83, 0x47, 0x87, 0x6f, 0x1f, 0x9c, 0x30, 0x79, 0xba, 0x98, 0x26, 0xa9, 0xc8, 0x06,
	0x2c, 0x3f, 0x4b, 0x4f, 0x09, 0xcb, 0xeb, 0x45, 0x2a, 0xb2, 0x4c, 0xe4, 0x03, 0x29, 0x04, 0x2f,
	0x07, 0x68, 0x81, 0x13, 0x29, 0xe6, 0x83, 0xda, 0xd1, 0xf4, 0x32, 0x7e, 0x47, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x9f, 0x60, 0xd4, 0x30, 0x7c, 0x06, 0x00, 0x00,
}
